# Generated by Django 4.1.5 on 2023-01-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_writer_delete_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
