# Generated by Django 4.1.5 on 2023-01-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_writer_blog_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
